[build]
  # Build command for React app with localStorage mode enabled
  command = "npm run build"

  # Directory containing the built files (relative to base)
  publish = "build"

  # Base directory for the build - Set to root for main app, or booking/client for booking app
  base = "."

[functions]
  # Directory where Netlify Functions are located
  directory = "netlify/functions"

# Environment variables
[build.environment]
  # Enable localStorage mode by default for Netlify deployments
  REACT_APP_USE_LOCAL_STORAGE = "true"
  # React app port (not used in production but good for consistency)
  PORT = "3000"
  # Disable ESLint plugin to prevent warnings from breaking build
  DISABLE_ESLINT_PLUGIN = "true"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

    # Cache control
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/static/*"
  [headers.values]
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

# Custom error pages (optional)
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404
